FrontendDemo/FrontendDemo/Models/Claim.cs
using System;
using System.Collections.Generic;

namespace FrontendDemo.Models
{
    public partial class Claim
    {
        public int? Id { get; set; }
        public string? PatientName { get; set; }
        public int? Age { get; set; }
        public string? ClaimCause { get; set; }
    }
}

FrontendDemo/FrontendDemo/Models/ErrorViewModel.cs
namespace FrontendDemo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FrontendDemo/FrontendDemo/Controllers/MediclaimController.cs
using FrontendDemo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;

namespace FrontendDemo.Controllers
{
    public class MediclaimController : Controller
    {

        string baseURL = "https://localhost:8080/api/mediclaims";
        static readonly HttpClient client = new HttpClient();

        // GET: Mediclaim
        public async Task<ActionResult> Index()
        {
            List<Claim> claimList = new List<Claim>();
            try
            {
                HttpResponseMessage response = await client.GetAsync(baseURL);
                response.EnsureSuccessStatusCode();
                claimList = await response.Content.ReadFromJsonAsync<List<Claim>>();
            }
            catch (HttpRequestException e)
            {
                Console.WriteLine("\nException Caught!");
                Console.WriteLine("Message :{0} ", e.Message);
            }

            return View(claimList);
        }
        public async Task<ActionResult> Details()
        {
            return View();
        }
        public async Task<ActionResult> Details_ClaimData(int id)
        {
            Claim responseBody;
            List<Claim> claimList = new List<Claim>();
            try
            {
                HttpResponseMessage response = await client.GetAsync(baseURL + "/" + id);
                response.EnsureSuccessStatusCode();
                responseBody = await response.Content.ReadFromJsonAsync<Claim>();
                claimList.Add(responseBody);
            }
            catch (HttpRequestException e)
            {
                Console.WriteLine("\nException Caught!");
                Console.WriteLine("Message :{0} ", e.Message);
            }
            return View(claimList);
        }


        // POST: Mediclaim/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Claim claim)
        {
            try
            {
                JsonSerializerOptions opt = new JsonSerializerOptions() { WriteIndented = true };
                string data = JsonSerializer.Serialize<Claim>(claim, opt);
                HttpContent content = new StringContent(data);
                content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                HttpResponseMessage response = await client.PostAsync(baseURL, content);
                response.EnsureSuccessStatusCode();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.Write(e);
                return RedirectToAction(nameof(Create));
            }
        }
        public ActionResult Create()
        {
            Claim claim = new Claim();
            return View(claim);
        }

        // GET: Mediclaim/Edit/5
        public ActionResult Edit()
        {
            return View();
        }

        public async Task<ActionResult> Edit_ClaimData(int id)
        {
            try
            {
                HttpResponseMessage response = await client.GetAsync(baseURL+"/"+id);
                response.EnsureSuccessStatusCode();
                Claim claim = await response.Content.ReadFromJsonAsync<Claim>();
                Console.WriteLine(claim);
                return View(claim);
            }
            catch
            {
                return RedirectToAction(nameof(Edit));
            }
        }

        public async Task<ActionResult> Edit_SubmitData(Claim claim)
        {
            try
            {
                JsonSerializerOptions opt = new JsonSerializerOptions() { WriteIndented = true};
                string data = JsonSerializer.Serialize<Claim>(claim, opt);
                HttpContent content = new StringContent(data);
                content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                HttpResponseMessage response = await client.PutAsync(baseURL+"/"+claim.Id, content);
                response.EnsureSuccessStatusCode();
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex);
                return RedirectToAction(nameof(Edit));
            }
        }

        // GET: Mediclaim/Delete/5
        public ActionResult Delete()
        {
            return View();
        }

        // POST: Mediclaim/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                HttpResponseMessage response = await client.DeleteAsync(baseURL+"/"+id);
                response.EnsureSuccessStatusCode();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Delete");
            }
        }
    }
}

FrontendDemo/FrontendDemo/Views/Mediclaim/Create.cshtml
@using FrontendDemo.Models
@model Claim

<h2>Create</h2>
<form asp-controller=Mediclaim asp-action=Create method="post">
            <div class="field">
                <div>
                    <label asp-for=Id>Patient Id :</label>
                </div>
                <div>
                    <input asp-for=Id type="number" />  
                </div>
            </div>
            <div class="field">
                <div>
                    <label asp-for=PatientName >Patient Name : </label>
                </div>
                <div>
                    <input asp-for=PatientName type="text"  />
                </div>
            </div>
            <div class="field">
                <div>
                    <label asp-for=Age>Patient Age : </label>
                </div>
                <div>
                    <input asp-for=Age type="number"  />
                </div>
            </div>
            <div class="field">
                <div>
                    <label asp-for=ClaimCause>Claim Cause : </label>
                </div>
                <div>
                    <input asp-for=ClaimCause type="text"  />
                </div>
            </div>
            <div class="field">
                <button type="submit">Create</button>
            </div>
</form>

FrontendDemo/FrontendDemo/Views/Mediclaim/Delete.cshtml
<h2>Delete</h2>
<form asp-controller=Mediclaim asp-action=Delete>
    <label>Enter the Patient ID : </label>
    <input name="id" type="number" />
    <button type="submit">Get Data</button>
</form>

FrontendDemo/FrontendDemo/Views/Mediclaim/Details.cshtml
<h2>Read by Id</h2>
<form asp-controller=Mediclaim asp-action=Details_ClaimData>
    <label>Enter the Patient ID : </label>
    <input name="id" type="number" />
    <button type="submit">Get Data</button>
</form>

FrontendDemo/FrontendDemo/Views/Mediclaim/Details_ClaimData.cshtml
@using FrontendDemo.Models
@model List<Claim>
<h2>Read by Id</h2>
<table>
    <thead class="thead-dark bg-black text-light">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Patient Name</th>
            <th scope="col">Age</th>
            <th scope="col">Claim Cause</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Claim item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.PatientName</td>
                <td>@item.Age</td>
                <td>@item.ClaimCause</td>
            </tr>
        }
    </tbody>
</table>

FrontendDemo/FrontendDemo/Views/Mediclaim/Edit.cshtml
<h2>Edit</h2>
<form asp-controller=Mediclaim asp-action=Edit_ClaimData>
    <label>Enter the Patient ID : </label>
    <input name="id" type="number" />
    <button type="submit">Get Data</button>
</form>

FrontendDemo/FrontendDemo/Views/Mediclaim/Edit_ClaimData.cshtml
@using FrontendDemo.Models
@model Claim

<h2>Edit</h2>
<form asp-controller=Mediclaim asp-action=Edit_SubmitData>
    <div class="field">
                <div>
                    <label asp-for=Id value=@Model.Id>Patient Id :</label>
                </div>
                <div>
                    <input asp-for=Id type="number" />  
                </div>
            </div>
            <div class="field">
                <div>
                    <label asp-for=PatientName >Patient Name : </label>
                </div>
                <div>
                    <input asp-for=PatientName type="text" value=@Model.PatientName />
                </div>
            </div>
            <div class="field">
                <div>
                    <lable asp-for=Age>Patient Age : </label>
                </div>
                <div>
                    <input asp-for=Age type="number"  value=@Model.Age/>
                </div>
            </div>
            <div class="field">
                <div>
                    <label asp-for=ClaimCause>Claim Cause : </label>
                </div>
                <div>
                    <input asp-for=ClaimCause type="text" value=@Model.ClaimCause/>
                </div>
            </div>
            <div class="field">
                <button type="submit">Create</button>
            </div>
</form>

FrontendDemo/FrontendDemo/Views/Mediclaim/Index.cshtml
@using FrontendDemo.Models
@model List<Claim>

@{
    ViewData["Title"] = "Read (Home)";
}

<table>
    <thead class="thead-dark bg-black text-light">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Patient Name</th>
            <th scope="col">Age</th>
            <th scope="col">Claim Cause</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Claim item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.PatientName</td>
                <td>@item.Age</td>
                <td>@item.ClaimCause</td>
            </tr>
        }
    </tbody>
</table>

FrontendDemo/FrontendDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MediClaim</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FrontendDemo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <h7>MediClaim</h7>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="bg-dark text-white nav-link" asp-area="" asp-controller="Mediclaim" asp-action="Create">Create</a>
                        </li>
                        <li class="nav-item">
                            <a class="bg-dark text-white nav-link" asp-area="" asp-controller="Mediclaim" asp-action="Index">Read</a>
                        </li>
                        <li class="nav-item">
                            <a class="bg-dark text-white nav-link" asp-area="" asp-controller="Mediclaim" asp-action="Details">Read By Id</a>
                        </li>
                        <li class="nav-item">
                            <a class=" bg-dark text-white nav-link" asp-area="" asp-controller="Mediclaim" asp-action="Edit">Update</a>
                        </li>
                        <li class="nav-item">
                            <a class=" bg-dark text-white nav-link" asp-area="" asp-controller="Mediclaim" asp-action="Delete">Delete</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>